package com.baileyanns.mileage;

import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import android.content.*;
import android.content.res.ColorStateList;
import java.text.SimpleDateFormat;
import java.util.*;

final class PremiumUi {
    private final MainActivity host;
    private final DatabaseHelper db;
    private final int GOLD=Color.rgb(217,140,0), BG=Color.rgb(1,14,29), CARD=Color.rgb(5,31,58), CARD_ALT=Color.rgb(6,38,70), LINE=Color.rgb(47,67,88), WHITE=Color.WHITE, MUTED=Color.rgb(192,201,212), GREEN=Color.rgb(112,210,75);
    private LinearLayout root;
    private String period="MONTH";
    private String screen="dashboard";
    private MileageGaugeView gauge;
    private TextView elapsedView;
    private final android.os.Handler handler=new android.os.Handler(android.os.Looper.getMainLooper());
    private final Runnable activeRefresh=new Runnable(){public void run(){if(!"active".equals(screen))return;DatabaseHelper.Trip t=db.activeTrip();if(t!=null){if(gauge!=null)gauge.setMiles(t.miles);if(elapsedView!=null)elapsedView.setText(elapsed(t.startedAt));handler.postDelayed(this,1000);}}};

    PremiumUi(MainActivity host,DatabaseHelper db){this.host=host;this.db=db;}

    void showDashboard(){
        shell("dashboard","",true);
        root.addView(periodTabs()); root.addView(space(12));
        Summary s=summary();
        LinearLayout r1=row();r1.addView(metric("M","TOTAL MILES",fmt(s.total)),weight(1));r1.addView(hgap());r1.addView(metric("#","TOTAL TRIPS",String.valueOf(s.count)),weight(1));root.addView(r1);root.addView(space(9));
        LinearLayout r2=row();r2.addView(metric("B","BUSINESS MILES",fmt(s.business)),weight(1));r2.addView(hgap());r2.addView(metric("E","ESTATE MILES",fmt(s.estate)),weight(1));root.addView(r2);root.addView(space(12));
        syncCard();root.addView(space(12));purposesCard(s.trips);root.addView(space(14));root.addView(primary("+  NEW TRIP",v->host.uiNewTrip()));
    }

    void showActive(){
        shell("active","TRIP ACTIVE",false);
        DatabaseHelper.Trip t=db.activeTrip();
        if(t==null){LinearLayout c=card(true);c.setGravity(Gravity.CENTER);c.setPadding(dp(20),dp(34),dp(20),dp(34));TextView car=text("CAR",20,GOLD,true);car.setGravity(Gravity.CENTER);c.addView(car);TextView n=text("No Active Trip",26,WHITE,true);n.setGravity(Gravity.CENTER);c.addView(n);TextView h=text("Start Estate Miles or Business Miles when you are ready to drive.",14,MUTED,false);h.setGravity(Gravity.CENTER);h.setPadding(dp(8),dp(6),dp(8),dp(12));c.addView(h);c.addView(primary("+  NEW TRIP",v->host.uiNewTrip()));root.addView(c);return;}
        gauge=new MileageGaugeView(host);gauge.setMiles(t.miles);root.addView(gauge,new LinearLayout.LayoutParams(-1,dp(270)));
        elapsedView=text(elapsed(t.startedAt),29,WHITE,true);elapsedView.setGravity(Gravity.CENTER);elapsedView.setPadding(0,0,0,0);root.addView(elapsedView);TextView e=text("ELAPSED TIME",11,MUTED,false);e.setGravity(Gravity.CENTER);e.setPadding(0,0,0,dp(18));root.addView(e);
        LinearLayout info=card(false);info.addView(detail("◷","START TIME",t.startTime));View line=new View(host);line.setBackgroundColor(LINE);info.addView(line,new LinearLayout.LayoutParams(-1,dp(1)));String p=t.purpose==null||t.purpose.isEmpty()?("ESTATE".equals(t.tripType)?t.estateName:"Business Miles"):t.purpose;info.addView(detail("●","PURPOSE",p));root.addView(info);root.addView(space(16));root.addView(primary("END TRIP",v->host.uiEndTrip()));handler.post(activeRefresh);
    }

    void showTrips(){
        shell("trips","TRIPS",false);List<DatabaseHelper.Trip> list=db.recentTrips(100);if(list.isEmpty()){TextView e=text("No completed trips yet.",16,MUTED,false);e.setGravity(Gravity.CENTER);e.setPadding(0,dp(30),0,dp(30));root.addView(e);}else{String last="";for(DatabaseHelper.Trip t:list){if(!Objects.equals(last,t.date)){last=t.date;TextView d=text(pretty(t.date),13,WHITE,true);d.setPadding(dp(3),dp(8),0,dp(7));root.addView(d);}root.addView(trip(t));root.addView(space(8));}}root.addView(space(8));root.addView(primary("+  NEW TRIP",v->host.uiNewTrip()));
    }

    void showReports(){
        shell("reports","REPORTS",false);LinearLayout c=card(true);c.addView(title("YEAR-END MILEAGE TAX REPORT"));EditText year=field("Tax Year");year.setInputType(2);year.setText(String.valueOf(Calendar.getInstance().get(Calendar.YEAR)));c.addView(year);TextView sum=text("",16,WHITE,true);sum.setPadding(0,dp(10),0,dp(10));c.addView(sum);Runnable calc=()->{try{int y=Integer.parseInt(year.getText().toString().trim());List<DatabaseHelper.Trip> list=db.tripsForYear(y);double e=0,b=0;for(DatabaseHelper.Trip t:list){if("ESTATE".equals(t.tripType))e+=t.miles;else b+=t.miles;}sum.setText(String.format(Locale.US,"Estate Miles     %.1f\nBusiness Miles   %.1f\nTotal Miles      %.1f",e,b,e+b));}catch(Exception ignored){}};calc.run();c.addView(secondary("REFRESH TOTALS",v->calc.run()));c.addView(space(8));c.addView(primary("PRINT YEAR-END REPORT",v->{try{int y=Integer.parseInt(year.getText().toString().trim());YearEndReport.print(host,YearEndReport.create(host,y,db.tripsForYear(y)),y);}catch(Exception ex){host.uiToast("Could not create report: "+ex.getMessage());}}));root.addView(c);root.addView(space(12));LinearLayout x=card(false);x.addView(title("MILEAGE BACKUP / EXPORT"));x.addView(text("Export all saved mileage to a CSV file for your records.",13,MUTED,false));x.addView(space(8));x.addView(secondary("EXPORT ALL MILEAGE (CSV)",v->host.uiExport()));root.addView(x);
    }

    void showMore(){
        shell("more","MORE",false);LinearLayout s=card(true);s.addView(title("BUSINESS MANAGER & CAR CONNECTION"));String st=Prefs.serverUrl(host).isEmpty()?"Not connected":"Business Manager connected";s.addView(text(st,14,Prefs.serverUrl(host).isEmpty()?GOLD:GREEN,true));s.addView(space(9));s.addView(primary("SYNC NOW",v->host.uiSync()));s.addView(space(8));s.addView(secondary("SETTINGS / CAR CONNECTION",v->host.uiSettings()));root.addView(s);root.addView(space(12));LinearLayout b=card(false);b.addView(title("BACKUP & EXPORT"));b.addView(text("Your automatic mileage backup remains enabled.",13,MUTED,false));b.addView(space(8));b.addView(secondary("EXPORT A COPY NOW",v->host.uiExport()));root.addView(b);
    }

    private void shell(String selected,String heading,boolean brand){
        screen=selected;handler.removeCallbacks(activeRefresh);gauge=null;elapsedView=null;LinearLayout outer=new LinearLayout(host);outer.setOrientation(LinearLayout.VERTICAL);outer.setBackgroundColor(BG);ScrollView scroll=new ScrollView(host);scroll.setFillViewport(true);scroll.setClipToPadding(false);root=new LinearLayout(host);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(12),dp(16),dp(24));root.setBackgroundColor(BG);scroll.addView(root,new ScrollView.LayoutParams(-1,-2));outer.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));if(brand)brandHeader();else pageHeader(heading);View div=new View(host);div.setBackgroundColor(LINE);outer.addView(div,new LinearLayout.LayoutParams(-1,dp(1)));outer.addView(bottom(selected),new LinearLayout.LayoutParams(-1,dp(72)));host.setContentView(outer);
    }

    private void brandHeader(){LinearLayout h=row();h.setGravity(Gravity.CENTER_VERTICAL);TextView menu=glyph("☰",26,WHITE);menu.setOnClickListener(v->showMore());h.addView(menu,new LinearLayout.LayoutParams(dp(38),dp(58)));ImageView icon=new ImageView(host);icon.setImageResource(com.baileyanns.mileage.R.drawable.miles_tracker_icon);icon.setScaleType(ImageView.ScaleType.CENTER_CROP);LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(dp(58),dp(58));ip.setMargins(dp(5),0,dp(10),0);h.addView(icon,ip);LinearLayout words=new LinearLayout(host);words.setOrientation(LinearLayout.VERTICAL);words.setGravity(Gravity.CENTER_VERTICAL);TextView n=text("Bailey Ann’s",25,WHITE,false);n.setTypeface(Typeface.create("serif",Typeface.NORMAL));n.setPadding(0,0,0,0);TextView sub=text("MILES TRACKER",11,GOLD,true);sub.setLetterSpacing(.18f);sub.setPadding(0,0,0,0);words.addView(n);words.addView(sub);h.addView(words,new LinearLayout.LayoutParams(0,dp(58),1));TextView more=glyph("⋮",28,WHITE);more.setOnClickListener(v->showMore());h.addView(more,new LinearLayout.LayoutParams(dp(34),dp(58)));root.addView(h);View line=new View(host);line.setBackgroundColor(GOLD);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(1));lp.setMargins(0,dp(7),0,dp(12));root.addView(line,lp);}
    private void pageHeader(String s){LinearLayout h=row();h.setGravity(Gravity.CENTER_VERTICAL);TextView back=glyph("‹",34,WHITE);back.setOnClickListener(v->showDashboard());h.addView(back,new LinearLayout.LayoutParams(dp(44),dp(52)));TextView t=text(s,18,WHITE,true);t.setGravity(Gravity.CENTER);t.setPadding(0,0,0,0);h.addView(t,new LinearLayout.LayoutParams(0,dp(52),1));TextView more=glyph("⋮",28,GOLD);more.setOnClickListener(v->showMore());h.addView(more,new LinearLayout.LayoutParams(dp(44),dp(52)));root.addView(h);root.addView(space(8));}
    private LinearLayout bottom(String sel){LinearLayout n=row();n.setBackgroundColor(Color.rgb(2,24,47));n.setPadding(dp(4),dp(5),dp(4),dp(4));n.addView(nav("⌂","Dashboard","dashboard".equals(sel),v->showDashboard()),weight(1));n.addView(nav("≡","Trips","trips".equals(sel),v->showTrips()),weight(1));n.addView(nav("●","Active Trip","active".equals(sel),v->showActive()),weight(1));n.addView(nav("▣","Reports","reports".equals(sel),v->showReports()),weight(1));n.addView(nav("•••","More","more".equals(sel),v->showMore()),weight(1));return n;}
    private LinearLayout nav(String g,String l,boolean on,View.OnClickListener click){int c=on?GOLD:WHITE;LinearLayout b=new LinearLayout(host);b.setOrientation(LinearLayout.VERTICAL);b.setGravity(Gravity.CENTER);b.setOnClickListener(click);TextView a=text(g,20,c,true);a.setGravity(Gravity.CENTER);a.setPadding(0,0,0,0);TextView t=text(l,10,c,on);t.setGravity(Gravity.CENTER);t.setPadding(0,0,0,0);t.setSingleLine(true);b.addView(a,new LinearLayout.LayoutParams(-1,dp(30)));b.addView(t,new LinearLayout.LayoutParams(-1,dp(24)));return b;}

    private LinearLayout periodTabs(){LinearLayout tabs=row();tabs.setPadding(dp(2),dp(2),dp(2),dp(2));tabs.setBackground(bg(Color.rgb(3,28,53),LINE,8));tabs.addView(tab("TODAY"),weight(1));tabs.addView(tab("MONTH"),weight(1));tabs.addView(tab("YEAR"),weight(1));return tabs;}
    private TextView tab(String p){TextView t=text(p,12,WHITE,true);t.setGravity(Gravity.CENTER);t.setPadding(0,0,0,0);if(p.equals(period))t.setBackground(bg(GOLD,GOLD,7));t.setOnClickListener(v->{period=p;showDashboard();});return t;}
    private LinearLayout metric(String g,String l,String v){LinearLayout c=card(false);c.setOrientation(LinearLayout.HORIZONTAL);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(12),dp(10),dp(12),dp(10));TextView icon=text(g,31,GOLD,true);icon.setGravity(Gravity.CENTER);icon.setTypeface(Typeface.create("serif",Typeface.BOLD));c.addView(icon,new LinearLayout.LayoutParams(dp(42),-1));LinearLayout w=new LinearLayout(host);w.setOrientation(LinearLayout.VERTICAL);w.setGravity(Gravity.CENTER_VERTICAL);TextView a=text(l,10,WHITE,true);a.setPadding(0,0,0,dp(2));TextView b=text(v,27,WHITE,true);b.setPadding(0,0,0,0);w.addView(a);w.addView(b);c.addView(w,new LinearLayout.LayoutParams(0,-1,1));return c;}
    private void syncCard(){int u=db.unsyncedCount();boolean connected=!Prefs.serverUrl(host).isEmpty();String st=!connected?"Not Connected":u>0?"Not Synced":"Synced";int sc=connected&&u==0?GREEN:GOLD;String d=!connected?"Connect in More":u>0?u+" trip"+(u==1?"":"s")+" need to be synced":"All saved trips are synced";LinearLayout c=card(true);c.setOnClickListener(v->host.uiSync());LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);TextView cloud=text("☁",30,WHITE,false);cloud.setGravity(Gravity.CENTER);r.addView(cloud,new LinearLayout.LayoutParams(dp(48),dp(54)));LinearLayout w=new LinearLayout(host);w.setOrientation(LinearLayout.VERTICAL);TextView a=text("SYNC STATUS",11,WHITE,true);a.setPadding(0,0,0,0);TextView b=text(st,18,sc,true);b.setPadding(0,0,0,0);TextView x=text(d,12,WHITE,false);x.setPadding(0,2,0,0);w.addView(a);w.addView(b);w.addView(x);r.addView(w,new LinearLayout.LayoutParams(0,-2,1));TextView ar=text("›",32,WHITE,false);ar.setGravity(Gravity.CENTER);r.addView(ar,new LinearLayout.LayoutParams(dp(30),dp(52)));c.addView(r);root.addView(c);}
    private void purposesCard(List<DatabaseHelper.Trip> trips){LinearLayout c=card(false);c.addView(title("TOP PURPOSES"));LinkedHashMap<String,Double> m=top(trips);if(m.isEmpty()){c.addView(text("No completed trips in this period.",13,MUTED,false));}else{double total=0;for(double v:m.values())total+=v;int i=0;for(Map.Entry<String,Double> e:m.entrySet()){int pct=total<=0?0:(int)Math.round(e.getValue()/total*100);LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);TextView n=text(e.getKey(),12,WHITE,false);n.setSingleLine(true);r.addView(n,new LinearLayout.LayoutParams(dp(110),dp(28)));LinearLayout bars=row();int safe=Math.max(2,Math.min(100,pct));View f=new View(host);f.setBackground(bg(i<2?GOLD:Color.rgb(165,171,178),Color.TRANSPARENT,5));bars.addView(f,new LinearLayout.LayoutParams(0,dp(9),safe));View rest=new View(host);rest.setBackground(bg(Color.rgb(22,48,75),Color.TRANSPARENT,5));bars.addView(rest,new LinearLayout.LayoutParams(0,dp(9),100-safe));r.addView(bars,new LinearLayout.LayoutParams(0,dp(28),1));TextView p=text(pct+"%",12,WHITE,true);p.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);r.addView(p,new LinearLayout.LayoutParams(dp(48),dp(28)));c.addView(r);i++;}}root.addView(c);}
    private LinkedHashMap<String,Double> top(List<DatabaseHelper.Trip> trips){Map<String,Double> m=new HashMap<>();for(DatabaseHelper.Trip t:trips){String p=t.purpose==null||t.purpose.trim().isEmpty()?("ESTATE".equals(t.tripType)?"Estate Sale":"Other"):t.purpose.trim();m.put(p,m.getOrDefault(p,0.0)+Math.max(0,t.miles));}List<Map.Entry<String,Double>> e=new ArrayList<>(m.entrySet());e.sort((a,b)->Double.compare(b.getValue(),a.getValue()));LinkedHashMap<String,Double> out=new LinkedHashMap<>();for(int i=0;i<Math.min(4,e.size());i++)out.put(e.get(i).getKey(),e.get(i).getValue());return out;}
    private static class Summary{double total,estate,business;int count;List<DatabaseHelper.Trip> trips=new ArrayList<>();}
    private Summary summary(){Summary s=new Summary();Calendar now=Calendar.getInstance(),start=(Calendar)now.clone();start.set(Calendar.HOUR_OF_DAY,0);start.set(Calendar.MINUTE,0);start.set(Calendar.SECOND,0);start.set(Calendar.MILLISECOND,0);if("MONTH".equals(period))start.set(Calendar.DAY_OF_MONTH,1);else if("YEAR".equals(period))start.set(Calendar.DAY_OF_YEAR,1);Calendar end=(Calendar)start.clone();if("TODAY".equals(period))end.add(Calendar.DAY_OF_MONTH,1);else if("MONTH".equals(period))end.add(Calendar.MONTH,1);else end.add(Calendar.YEAR,1);long a=start.getTimeInMillis(),b=end.getTimeInMillis();for(DatabaseHelper.Trip t:db.allTrips())if(t.startedAt>=a&&t.startedAt<b){s.trips.add(t);s.count++;s.total+=t.miles;if("ESTATE".equals(t.tripType))s.estate+=t.miles;else s.business+=t.miles;}return s;}

    private LinearLayout trip(DatabaseHelper.Trip t){LinearLayout c=card(false);c.setPadding(dp(13),dp(10),dp(10),dp(9));LinearLayout a=row();a.setGravity(Gravity.CENTER_VERTICAL);String name=t.purpose!=null&&!t.purpose.isEmpty()?t.purpose:("ESTATE".equals(t.tripType)&&t.estateName!=null&&!t.estateName.isEmpty()?t.estateName:"Business Miles");TextView n=text(name,16,WHITE,true);n.setSingleLine(true);a.addView(n,new LinearLayout.LayoutParams(0,dp(32),1));TextView mi=text(fmt(t.miles)+" mi",15,WHITE,true);mi.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);a.addView(mi,new LinearLayout.LayoutParams(dp(74),dp(32)));TextView more=glyph("⋮",24,MUTED);more.setOnClickListener(v->menu(v,t));a.addView(more,new LinearLayout.LayoutParams(dp(28),dp(32)));c.addView(a);LinearLayout b=row();TextView time=text(t.startTime+(t.endTime==null||t.endTime.isEmpty()?"":" – "+t.endTime),12,WHITE,false);time.setPadding(0,0,0,0);b.addView(time,new LinearLayout.LayoutParams(0,dp(27),1));TextView sync=text(t.synced==1?"Synced":"Not Synced",12,t.synced==1?GREEN:GOLD,false);sync.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);sync.setPadding(0,0,0,0);b.addView(sync,new LinearLayout.LayoutParams(dp(92),dp(27)));c.addView(b);return c;}
    private void menu(View anchor,DatabaseHelper.Trip t){PopupMenu p=new PopupMenu(host,anchor);p.getMenu().add("Edit Trip");p.getMenu().add("Delete Trip");p.setOnMenuItemClickListener(item->{if("Edit Trip".contentEquals(item.getTitle()))host.uiEdit(t);else host.uiDelete(t);return true;});p.show();}
    private LinearLayout detail(String g,String l,String v){LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(0,dp(9),0,dp(9));TextView a=text(g,22,WHITE,false);a.setGravity(Gravity.CENTER);r.addView(a,new LinearLayout.LayoutParams(dp(38),dp(42)));TextView b=text(l,12,WHITE,true);r.addView(b,new LinearLayout.LayoutParams(0,dp(42),1));TextView c=text(v,15,WHITE,false);c.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);r.addView(c,new LinearLayout.LayoutParams(0,dp(42),1.4f));return r;}

    private LinearLayout row(){LinearLayout l=new LinearLayout(host);l.setOrientation(LinearLayout.HORIZONTAL);return l;}private LinearLayout.LayoutParams weight(float w){return new LinearLayout.LayoutParams(0,dp(106),w);}private View hgap(){Space s=new Space(host);s.setLayoutParams(new LinearLayout.LayoutParams(dp(9),1));return s;}private LinearLayout card(boolean gold){LinearLayout c=new LinearLayout(host);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(14),dp(14),dp(14));c.setBackground(bg(CARD,gold?GOLD:LINE,10));return c;}private GradientDrawable bg(int fill,int stroke,int radius){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(radius));if(stroke!=Color.TRANSPARENT)g.setStroke(dp(1),stroke);return g;}private Button primary(String s,View.OnClickListener l){return button(s,l,true);}private Button secondary(String s,View.OnClickListener l){return button(s,l,false);}private Button button(String s,View.OnClickListener l,boolean primary){Button b=new Button(host);b.setText(s);b.setAllCaps(false);b.setTextSize(15);b.setTypeface(Typeface.DEFAULT_BOLD);b.setTextColor(primary?WHITE:GOLD);b.setBackground(bg(primary?GOLD:CARD_ALT,GOLD,8));b.setPadding(dp(12),dp(11),dp(12),dp(11));b.setMinHeight(dp(50));b.setOnClickListener(l);return b;}private TextView text(String s,float z,int c,boolean bold){TextView t=new TextView(host);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);t.setPadding(0,dp(3),0,dp(4));return t;}private TextView glyph(String s,float z,int c){TextView t=text(s,z,c,false);t.setGravity(Gravity.CENTER);t.setPadding(0,0,0,0);return t;}private TextView title(String s){TextView t=text(s,13,WHITE,true);t.setLetterSpacing(.08f);t.setPadding(0,0,0,dp(8));return t;}private EditText field(String h){EditText e=new EditText(host);e.setHint(h);e.setHintTextColor(MUTED);e.setTextColor(WHITE);e.setSingleLine(true);e.setBackgroundTintList(ColorStateList.valueOf(GOLD));return e;}private View space(int h){Space s=new Space(host);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return s;}private int dp(int x){return (int)(x*host.getResources().getDisplayMetrics().density+.5f);}private String fmt(double x){return String.format(Locale.US,"%.1f",x);}private String elapsed(long start){long s=Math.max(0,(System.currentTimeMillis()-start)/1000),h=s/3600,m=(s%3600)/60;return String.format(Locale.US,"%02d:%02d:%02d",h,m,s%60);}private String pretty(String raw){try{SimpleDateFormat in=new SimpleDateFormat("yyyy-MM-dd",Locale.US),out=new SimpleDateFormat("MMM d, yyyy",Locale.US);return out.format(Objects.requireNonNull(in.parse(raw))).toUpperCase(Locale.US);}catch(Exception e){return raw==null?"":raw.toUpperCase(Locale.US);}}

    private static class MileageGaugeView extends View{private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);private double miles;MileageGaugeView(Context c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}void setMiles(double v){miles=v;invalidate();}@Override protected void onDraw(Canvas c){float w=getWidth(),h=getHeight(),cx=w/2f,cy=h*.5f,r=Math.min(w,h)*.37f;RectF box=new RectF(cx-r,cy-r,cx+r,cy+r);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(10);p.setStrokeCap(Paint.Cap.ROUND);p.setColor(Color.rgb(47,67,88));c.drawArc(box,135,270,false,p);p.setColor(Color.rgb(217,140,0));p.setShadowLayer(12,0,0,p.getColor());c.drawArc(box,135,270,false,p);p.clearShadowLayer();p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setColor(Color.WHITE);p.setTextSize(20);c.drawText("CAR",cx,cy-r*.42f,p);p.setTextSize(57);c.drawText(String.format(Locale.US,"%.1f",miles),cx,cy+18,p);p.setTextSize(18);c.drawText("MILES",cx,cy+52,p);}}
}
